name: luxly-dev

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingtimeouts.readtimeout=60"
    ports:
      - "80:80"     
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - luxly-net

  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - luxly-net

  valkey:
    image: valkey/valkey:7.2
    command: valkey-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/valkey:/data
    networks:
      - luxly-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./docker/data/minio:/data
    networks:
      - luxly-net

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    env_file:
      - .env 
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - valkey
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_HOST}`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
    networks:
      - luxly-net

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - valkey
      - minio
    networks:
      - luxly-net

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    environment:
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_URL=http://${WEB_HOST}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    networks:
      - luxly-net

networks:
  luxly-net:
    driver: bridge